environment: development
app:
  host: 0.0.0.0
  port: 8000
  log_level: info
  max_concurrency: 100
  request_timeout_s: 30

postgres:
  dsn: postgresql://readonly:readonly@localhost:5432/analytics
  min_pool_size: 5
  max_pool_size: 20
  statement_timeout_ms: 5000
  sample_limit: 500
  max_limit: 1000

redis:
  url: redis://localhost:6379/0
  schema_cache_ttl_s: 7200
  embedding_cache_ttl_s: 86400

llm:
  provider: openai
  model: gpt-4o-mini
  temperature: 0.0
  max_tokens: 1200
  rate_limit_per_minute: 100
  reasoner_retry_config:
    attempts: 3
    backoff_seconds: 2
  synthesizer_retry_config:
    attempts: 3
    backoff_seconds: 2

schema:
  refresh_interval_s: 3600
  max_schema_slice_bytes: 8192
  ranker_top_n: 8
  fk_depth: 2

sql_guardrails:
  row_threshold: 500000
  cost_threshold: 100000
  max_estimated_time_ms: 2000
  require_where_for_large_tables: true
  disallowed_functions:
    - pg_sleep
    - dblink_connect

observability:
  enable_tracing: true
  service_name: isaqe
  metrics_port: 9000
  audit_log_path: logs/audit.log

security:
  enforce_read_only_role: true
  enable_rate_limiting: true
  max_requests_per_minute: 60
  ip_whitelist: []

prompts:
  examples_path: prompts/prompt_examples.json
  reasoner_schema: prompts/reasoner_schema.json
  synthesizer_schema: prompts/synthesizer_schema.json
